#!/bin/bash

# Конвертация шрифтов Type1, сделанных Fontografer (ANSI-encoding) 
# для работы в TeX

#!/bin/sh
for f in *.afm; do
    base=`basename $f .afm`
    echo "Convertig $base ..."
    afm2tfm $f -v $base.vpl -p fontogr.enc $base.tfm > $base.tmp
    tftopl $base.tfm $base.pl
    cat ligtable.rus >> $base.pl
    pltotf $base.pl $base.tfm
done
cat *.tmp > 000.tmp
sed 's/\(^[a-z]*\)\(_*\)\( .*$\)/\1\3 \<\1\2.pfb/g' 000.tmp > fontogr.map
rm -f *.pl *.vpl *.tmp

